name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Use Node 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Create release pull request or publish to npm
        id: changesets
        # https://github.com/changesets/action
        uses: changesets/action@master
        with:
          title: 'chore: publish release'
          # This expects you to have a script called release which does a build
          # for your packages and calls changeset publish
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
